name: Generate engineering_blogs.opml file

on: [push, pull_request]

jobs:
  generate:
    name: Generate engineering_blogs.opml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # ← fixes detached HEAD

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install pkgs
        run: bundle install --jobs 4

      - name: Generate opml file using ruby
        run: ruby generate_opml.rb

      - name: Auto-Commit engineering_blogs file if updated
        uses: stefanzweifel/git-auto-commit-action@v4.1.5
        with:
          commit_message: Commit by Github WorkFlow
          file_pattern: engineering_blogs.opml
          branch: ${{ github.head_ref }}  # ← fixes push to detached HEAD
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: g1patil <g1patil@users.noreply.github.com>